### ISSUE TITLE
Error java.lang.NoSuchMethodError: clojure.lang.RT.mapUniqueKeys when starting topology

### ISSUE THREAD

**Issue by lospejos** [wurstmeister/storm-kafka-0.8-plus-test#5]
Hi!
I've built successfully project "storm-kafka-0.8-plus-test-master" with maven, but when attempted to start a demo with:
java -cp target\storm-kafka-0.8-plus-test-0.2.0-SNAPSHOT-jar-with-dependencies.jar storm.kafka.KafkaSpoutTestTopology %ZOOKEEPER%
catched an error:
 java.lang.NoSuchMethodError: clojure.lang.RT.mapUniqueKeys

I'm not familiar with Clojure, but I suppose the root cause is Clojure version. Currently my .m2\repository\org\clojure\clojure\ folder contains 1.2.0, 1.2.1 till 1.5.1 Clojure versions. I suppose maven build script  added incorrect clojure version classes to storm-kafka-0.8-plus-test-0.2.0-SNAPSHOT-jar-with-dependencies.jar 
Could you please check it? Probably this is already solved?

**Comment by wurstmeister** [comment]
Hi, 

sorry for the late reply. I've updated the dependencies

Thanks
